{{- $image := .Values.gateway.rolloutJob.image }}
{{- if .Values.global }}
{{- $image = merge .Values.gateway.rolloutJob.image .Values.global.image }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: resource-rollout
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5" # run this job after the role/rolebinding is created
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      labels:
        gloo: resource-rollout
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      serviceAccountName: gloo-resource-rollout
      containers:
        - name: kubectl
          image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.gateway.rolloutJob.floatingUserId }}
            runAsUser: {{ printf "%.0f" (float64 .Values.gateway.rolloutJob.runAsUser) -}}
            {{- end }}
          command:
          - /bin/sh
          - -c
          - |
            {{- if and .Values.gateway.enabled .Values.gateway.validation.enabled .Values.gateway.validation.webhook.enabled }}
            # if validation webhook is enabled, wait for deployment rollout so validation service will be available
            kubectl rollout status deployment -n {{ .Release.Namespace }} gloo
            {{- end -}}

            {{- if .Release.IsUpgrade }}
            # remove existing helm labels/annotations since the custom resources are no longer managed by helm
            {{- range list "gateways.gateway.solo.io" "upstreams.gloo.solo.io" }}
            kubectl annotate {{ . }} -n {{ $.Release.Namespace }} --all helm.sh/hook-
            kubectl annotate {{ . }} -n {{ $.Release.Namespace }} --all helm.sh/hook-weight-
            kubectl annotate {{ . }} -n {{ $.Release.Namespace }} --all meta.helm.sh/release-name-
            kubectl annotate {{ . }} -n {{ $.Release.Namespace }} --all meta.helm.sh/release-namespace-
            kubectl label {{ . }} -n {{ $.Release.Namespace }} -l app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by-
            {{- end -}}
            {{- end -}}{{/* if .Release.IsUpgrade */}}

            # apply Gloo Edge custom resources
            kubectl apply -f - <<EOF{{- include "gloo.customResources" . | indent 12}}EOF
      restartPolicy: Never
  ttlSecondsAfterFinished: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0" # must be created before rollout job
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0" # must be created before rollout job
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0" # must be created before rollout job
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
roleRef:
  kind: Role
  name: gloo-resource-rollout
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
